steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.proactive'
      - '-t'
      - 'gcr.io/$PROJECT_ID/proactive-risk-assessment:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/proactive-risk-assessment:latest'
      - '.'
    dir: 'src/prediction'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/proactive-risk-assessment']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'proactive-risk-assessment'
      - '--image=gcr.io/$PROJECT_ID/proactive-risk-assessment:$COMMIT_SHA'
      - '--region=europe-west2'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--set-env-vars=GCP_PROJECT=$PROJECT_ID,MODEL_BUCKET=$PROJECT_ID-cqc-ml-artifacts,MODEL_PATH=models/proactive/model_package.pkl'
      - '--allow-unauthenticated'

# Build timeout
timeout: 1200s

# Artifacts to store
images:
  - 'gcr.io/$PROJECT_ID/proactive-risk-assessment:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/proactive-risk-assessment:latest'