steps:
  # Run BigQuery SQL to load synthetic data
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bq'
    args: ['query', '--use_legacy_sql=false', '--project_id=$PROJECT_ID']
    dir: 'sql'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    secretEnv: []
    id: 'load-synthetic-data'
    waitFor: ['-']
    script: |
      cat load_synthetic_data.sql