steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cqc-bigquery-loader', '-f', 'Dockerfile.process', '.']
    dir: 'scripts'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cqc-bigquery-loader']

  # Deploy to Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'cqc-bigquery-loader'
      - '--image=gcr.io/$PROJECT_ID/cqc-bigquery-loader'
      - '--region=europe-west2'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--task-timeout=3600'
      - '--parallelism=1'
      - '--max-retries=1'
      - '--service-account=744974744548-compute@developer.gserviceaccount.com'
      - '--set-env-vars=GCP_PROJECT=$PROJECT_ID'

  # Execute the job immediately after deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - 'cqc-bigquery-loader'
      - '--region=europe-west2'
      - '--wait'

images:
  - 'gcr.io/$PROJECT_ID/cqc-bigquery-loader'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY