steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cqc-data-fetcher:latest', '-f', 'scripts/Dockerfile.fetcher', 'scripts/']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cqc-data-fetcher:latest']

  # Deploy to Cloud Run as a job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'cqc-data-fetcher'
      - '--image=gcr.io/$PROJECT_ID/cqc-data-fetcher:latest'
      - '--region=europe-west2'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--max-retries=1'
      - '--timeout=30m'
      - '--service-account=cqc-ml-processor@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=GCP_PROJECT=$PROJECT_ID,GCS_BUCKET=$PROJECT_ID-cqc-raw-data,MAX_LOCATIONS=1000'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'