steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cqc-data-fetcher-enhanced', '.']
    dir: 'src/ingestion'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cqc-data-fetcher-enhanced']

  # Deploy to Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'replace'
      - '--image=gcr.io/$PROJECT_ID/cqc-data-fetcher-enhanced'
      - '--region=europe-west2'
      - '--task-timeout=3600'
      - '--max-retries=3'
      - '--parallelism=1'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--service-account=cqc-fetcher@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=MAX_LOCATIONS=1000,BATCH_SIZE=100'
      - '--'
      - 'cqc-data-fetcher-enhanced'

# Build configuration options
options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: 1200s